#!/bin/bash

#SBATCH --partition=rome
#SBATCH --job-name=download-imagenet
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=4:00:00
#SBATCH --output=output/download-imagenet_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/uva_fact_2024/

# activate the environment
source activate fact2024

# install additional packages
pip install kaggle

# verify installation
kaggle competitions download -c imagenet-object-localization-challenge
