#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/uva_fact_2024/
conda env create -f fact2024.yml

# activate the environment
source activate fact2024

# install additional packages
pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git
pip install wandb

# verify installation
python -c "import clip; print(f'CLIP available models: {clip.available_models()}')"